version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - local-network
networks:
  local-network:
    driver:
      bridge